### ISSUE TITLE
Customizer unlock/recipe support

### ISSUE THREAD

**Issue by budak7273** [Jarno458/SatisfactoryArchipelagoMod#11]
The availability of the base game's Customizer recipes (building materials and skins in the AWESOME Shop) are closely tied to specific base-game unlocks that award them, we will have to do some shenanigans with adjusting their dependencies to ensure they still become available at the right timing

**Comment by budak7273** [comment]
Will likely be affected by SML content registration bug: https://github.com/satisfactorymodding/SatisfactoryModLoader/issues/248

Need to use the workaround mentioned there to ensure the schematics display correctly to the user

**Comment by Jarno458** [comment]
Sofar quite a few are already working
Here we are actually awarding the basegame schematics rather than Ap specific ones, so that solves that depency issue aswel

**Comment by Jarno458** [comment]
Currently if it works the way i intended to, all customizer stuff should be available or purchaseable from awsome shop
it does not become available at specific moments, and i dont think we should invest time on that
