### ISSUE TITLE
AP Gifting Portal v1

### ISSUE THREAD

**Issue by budak7273** [Jarno458/SatisfactoryArchipelagoMod#32]
- [x] Saving of what player is selected as the portal target
- [ ] Gift receiving needs to turn off early in to the game quit process and pause for the game save process to avoid the server thinking items have been delivered when they haven't yet
- [x] Gifting System needs to save the items that have been received from the server but not yet sent out onto belts

**Comment by budak7273** [comment]
Gifting System needs to save the items that have been received from the server but not yet sent out onto belts

**Comment by Jarno458** [comment]
Gifting isn't waterproof and it doesn't have to be, there will never be something gifted you absolutely need
