### ISSUE TITLE
Wrong icon on mam nodes on jarno's side

### ISSUE THREAD

**Issue by budak7273** [Jarno458/SatisfactoryArchipelagoMod#63]
Not sure the details on this, should have kept more notes rip

![Image](https://github.com/Jarno458/SatisfactoryArchipelagoMod/assets/25965766/4e35246b-3a02-4d64-bfd3-2ffec1181d13)

**Comment by Jarno458** [comment]
I did look into this before, it seems to have the correct itemid and is correctly set in mam tree, but it seems to have 0 rewards so its not getting picked up by code, ill have to check spoiler to see if anything is generated there

**Comment by Jarno458** [comment]
Scope wise this only seems to affect the beacon agaric,
