### ISSUE TITLE
Milestone display names that appear in Free Samples award log are ugly ("AP_ItemId_1338277")

### ISSUE THREAD

**Issue by budak7273** [Jarno458/SatisfactoryArchipelagoMod#74]

**Comment by Jarno458** [comment]
True but not much to fix here i guess, unless we can hide those messages and maybe put a different message up

**Comment by Jarno458** [comment]
Maybe this can be fixed inside free samples or maybe i should add actual names to those AP schematics

**Comment by budak7273** [comment]
Needs the schematics to be given human readable display names on the AP side

**Comment by Jarno458** [comment]
oke ill add that
