### ISSUE TITLE
Make sure the "initial ore scanning" schematic that is auto granted to the player is visible in the hub to "explain" why they're unlocked

### ISSUE THREAD

**Issue by budak7273** [Jarno458/SatisfactoryArchipelagoMod#80]

**Comment by Jarno458** [comment]
We can do this, but personally i fear it spark more questions when it fixes. like i think its clear to a the user who hits the scan button that they see all posable scans are there. afterall your are expected to know the basegame and not play the rando as your first experience

but if we do add this, i expect questions like why doesn't it show all my starting inventory expansion or my starting inventory buildings or other stuff like that
